sudo: false
language: cpp
os:
  - linux
  - osx
env:
  - DEFINES=PUGIXML_NO_CXX11
  - DEFINES=PUGIXML_NO_CXX11,PUGIXML_WCHAR_MODE
  - DEFINES=PUGIXML_NO_CXX11,PUGIXML_COMPACT
script:
  - make test config=coverage defines=$DEFINES -j2
  - make test config=release defines=$DEFINES -j2

after_success: bash <(curl -s https://codecov.io/bash) -f pugixml.cpp.gcov
