CXXFLAGS=-c -Wall -Wextra -Werror -pedantic

BUILD=build/travis

SOURCES=src/pugixml.cpp $(wildcard tests/*.cpp)
OBJECTS=$(SOURCES:%=$(BUILD)/%.o)
EXECUTABLE=$(BUILD)/test

all: $(EXECUTABLE)

test: $(EXECUTABLE)
	./$(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
	$(CXX) $(OBJECTS) $(LDFLAGS) -o $@

$(BUILD)/%.cpp.o: %.cpp
	mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) $< -o $@

clean:
	rm -rf $(BUILD)

.PHONY: all test clean